language: python
python:
    - '3.8'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/KathyP825/demo-repo2

script:
    - make tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
    api_key:
    app: swe-demo-repo2
    on: $HEROKU_API_KEY
        branch: master

# after_success:
#    - ./deploy.sh
# 
# notifications:
#  slack: devopsnyu:vAFcJBgAP2f73SqhWgb40Gjf